runtime: nodejs14

env_variables:
  NODE_ENV: production 

handlers:
- url: /static
  static_dir: static

# To enable /demos *and* /demos/
- url: /demos(/)?
  static_files: demos/index.html
  upload: demos/index.html

# To enable index.html on a directory, eg: 
# https://notations.appspot.com/demos/posts/my-first-post/
- url: /demos/(.*)/
  static_files: demos/\1/index.html
  upload: demos/(.*)/index.html

# All other non-folder files
- url: /demos/(.*)
  static_files: demos/\1
  upload: demos/(.*)

## By default - goto "homepage" folder
- url: (/)?
  static_files: homepage/index.html
  upload: homepage/index.html

# To enable index.html on a directory, eg: 
# https://galorium.appspot.com/blog/posts/my-first-post/
- url: /(.*)/
  static_files: homepage/\1/index.html
  upload: homepage/(.*)/index.html

# All other non-folder files
- url: /(.*)
  static_files: homepage/\1
  upload: homepage/(.*)

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
