// Supported grammars for different langauges
export const builtinGrammars = [
  {
    name: "JSON",
    label: "JSON",
    selected: true,
    grammar: `
        %token NUMBER /-?\\d+(\\.\\d+)?([eE][+-]?\\d+)?/
        %token STRING /".*?(?<!\\\\)"/
        %skip /[ \\t\\n\\f\\r]+/

        Value -> Dict | List | STRING | NUMBER | Boolean | "null" ;
        List -> "[" [ Value ( "," Value ) * ] "]" ;
        Dict -> "{" [ Pair ("," Pair)* ] "}" ;
        Pair -> STRING ":" Value ;
        Boolean -> "true" | "false" ;
    `,
  },
];
/*
  settings: {
    popoutWholeStack: true,
    blockedPopoutsThrowError: true,
    closePopoutsOnUnload: true,
    hasHeaders: true,
    showPopoutIcon: true,
    showMaximiseIcon: true,
    showMinimiseIcon: true,
  },
 */

// Default config for golden-layout windows
export const defaultGLConfig: any = {
  root: {
    type: "column",
    content: [
      {
        type: "row",
        content: [
          {
            type: "stack",
            content: [
              {
                type: "component",
                content: [],
                width: 50,
                minWidth: 0,
                height: 50,
                minHeight: 0,
                id: "",
                maximised: false,
                isClosable: true,
                reorderEnabled: true,
                title: "Grammar",
                componentType: "grammarArea",
                componentState: {
                },
              },
              {
                type: "component",
                content: [],
                width: 50,
                minWidth: 0,
                height: 50,
                minHeight: 0,
                id: "",
                maximised: false,
                isClosable: true,
                reorderEnabled: true,
                title: "Normalized Grammar",
                componentType: "normalizedGrammarArea",
                componentState: {},
              },
            ],
            width: 49.99999999999999,
            minWidth: 0,
            height: 50,
            minHeight: 0,
            id: "",
            isClosable: true,
            maximised: false,
            activeItemIndex: 0,
          },
          {
            type: "stack",
            content: [
              {
                type: "component",
                content: [],
                width: 50,
                minWidth: 0,
                height: 50,
                minHeight: 0,
                id: "",
                maximised: false,
                isClosable: true,
                reorderEnabled: true,
                title: "Parse Table",
                componentType: "ptableArea",
                componentState: {},
              },
            ],
            width: 49.99999999999999,
            minWidth: 0,
            height: 50,
            minHeight: 0,
            id: "",
            isClosable: true,
            maximised: false,
            activeItemIndex: 0,
          },
        ],
        width: 50,
        minWidth: 0,
        height: 36.88840024819328,
        minHeight: 0,
        id: "",
        isClosable: true,
      },
      {
        type: "row",
        content: [
          {
            type: "stack",
            content: [
              {
                type: "component",
                content: [],
                width: 50,
                minWidth: 0,
                height: 50,
                minHeight: 0,
                id: "",
                maximised: false,
                isClosable: true,
                reorderEnabled: true,
                title: "Input",
                componentType: "inputArea",
                componentState: {
                  "contents2": `{"a":"b"}`,
                  "contents": `{
  "name": "Milky Way",
  "age": 4600000000,
  "star": "sun",
  "planets": [ "Mercury", "Venus", "Earth" ],
  "hot": true,
  "x": null
}
`
                },
              },
            ],
            width: 50,
            minWidth: 0,
            height: 50,
            minHeight: 0,
            id: "",
            isClosable: true,
            maximised: false,
            activeItemIndex: 0,
          },
          {
            type: "stack",
            content: [
              {
                type: "component",
                content: [],
                width: 50,
                minWidth: 0,
                height: 50,
                minHeight: 0,
                id: "",
                maximised: false,
                isClosable: true,
                reorderEnabled: true,
                title: "Parse Tree",
                componentType: "ptreeArea",
                componentState: {},
              },
            ],
            width: 50,
            minWidth: 0,
            height: 50,
            minHeight: 0,
            id: "",
            isClosable: true,
            maximised: false,
            activeItemIndex: 0,
          },
        ],
        width: 50,
        minWidth: 0,
        height: 39.12151503605394,
        minHeight: 0,
        id: "",
        isClosable: true,
      },
      {
        type: "stack",
        content: [
          {
            type: "component",
            content: [],
            width: 50,
            minWidth: 0,
            height: 50,
            minHeight: 0,
            id: "",
            maximised: false,
            isClosable: true,
            reorderEnabled: true,
            title: "Console",
            componentType: "consoleArea",
            componentState: {},
          },
        ],
        width: 50,
        minWidth: 0,
        height: 23.990084715752772,
        minHeight: 0,
        id: "",
        isClosable: true,
        maximised: false,
        activeItemIndex: 0,
      },
    ],
    width: 50,
    minWidth: 0,
    height: 50,
    minHeight: 0,
    id: "",
    isClosable: true,
  },
  openPopouts: [],
  settings: {
    constrainDragToContainer: true,
    reorderEnabled: true,
    popoutWholeStack: false,
    blockedPopoutsThrowError: true,
    closePopoutsOnUnload: true,
    responsiveMode: "none",
    tabOverlapAllowance: 0,
    reorderOnTabMenuClick: true,
    tabControlOffset: 10,
    popInOnClose: false,
  },
  dimensions: {
    borderWidth: 5,
    borderGrabWidth: 5,
    minItemHeight: 10,
    minItemWidth: 10,
    headerHeight: 20,
    dragProxyWidth: 300,
    dragProxyHeight: 200,
  },
  header: {
    show: "top",
    popout: "open in new window",
    dock: "dock",
    close: "close",
    maximise: "maximise",
    minimise: "minimise",
    tabDropdown: "additional tabs",
  },
  resolved: true,
};
